name: password_app_2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # install
  json_serializable: ^6.2.0
  flutter_launcher_icons: ^0.9.3
  flutter_riverpod: ^1.0.0
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^2.0.3
  fluttertoast: ^8.0.9
  freezed: ^2.0.3+1
  local_auth: ^2.1.0
  passcode_screen: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  # install
  build_runner: ^2.1.11


flutter:
  uses-material-design: true

  assets:
  - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"