name: password_app_2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  app_tracking_transparency: ^2.0.2+4
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.0
  flutter_secure_storage: ^5.0.2
  fluttertoast: ^8.0.9
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  google_mobile_ads: ^1.3.0
  intl: "^0.17.0"

  # install
  json_serializable: ^6.2.0
  local_auth: ^2.1.0
  passcode_screen: ^2.0.1

dev_dependencies:
  build_runner: ^2.1.11

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

  import_path_converter: ^1.0.1
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

import_path_converter:
  relative: true
